version: '3.8'

services:
  node-app:
    container_name: "express"
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    environment:
      - APP_PORT=${APP_PORT}
      - APP_KEY=${APP_KEY}
      - MONGO_URL=${MONGO_URL}
    ports:
      - '${APP_PORT}:8080'
    volumes:
      - .:/src
      - '/node_modules'
    depends_on:
      - mongodb
    networks:
      - backend-network

  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=express-app
      - MONGO_INITDB_USER=AdamDev
      - MONGO_INITDB_PWD=AdamDevPassword
      - MONGO_AUTH=SCRAM-SHA-256
    ports:
      - '${MONGO_PORT_OUTSIDE}:27017'
    volumes:
          - ./docker/mongodb/init.sh/:/docker-entrypoint-initdb.d/init.sh
          - mongo-v:/data/db
    networks:
      - backend-network

volumes:
  mongo-v:

networks:
  backend-network: