version: '3.8'

services:
  node-app:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/src
      - '/node_modules'
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge