version: '3.8'

services:
  node-app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    environment:
      - APP_KEY=${APP_KEY}
      - APP_MONGO_URL=${APP_MONGO_URL}
      - APP_EXPOSE_PORT=${APP_PORT_INSIDE}
    ports:
      - '${APP_PORT_OUTSIDE}:${APP_PORT_INSIDE}'
    volumes:
      - .:/src
      - '/node_modules'
    depends_on:
      - mongodb
    networks:
      - backend-network

  mongodb:
    container_name: ${MONGO_CONTAINER_NAME}
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - '${MONGO_PORT_OUTSIDE}:${MONGO_PORT_INSIDE}'
    volumes:
          - mongo-v:/data/db
    networks:
      - backend-network

volumes:
  mongo-v:

networks:
  backend-network: